# Generated by Django 6.0.7 on 2026-07-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0014_product_supplier_name_product_supplier_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_product_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('supplier_stock', models.IntegerField(default=0)),
                ('supplier_synced_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_response', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='BestLogMarketPlaceApp.product')),
            ],
        ),
    ]
