# Generated by Django 6.0.7 on 2026-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0015_supplierproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('approved', 'approved'), ('declined', 'declined')], default='pending', max_length=20),
        ),
    ]
