# Generated by Django 6.0.7 on 2026-07-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0016_alter_product_supplier_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='delivered_keys_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
