# Generated by Django 6.0.7 on 2026-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0017_supplierproduct_delivered_keys_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivered_keys_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
