# Generated by Django 6.0.7 on 2026-07-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0018_transaction_delivered_keys_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='supplier_category_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_category_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
