# Generated by Django 6.0.7 on 2026-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0021_storecategory_product_store_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_category',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StoreCategory',
        ),
    ]
