# Generated by Django 5.0.14 on 2026-07-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestLogMarketPlaceApp', '0023_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sqlite_to_postgres', max_length=100, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('total_objects', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Data Import Marker',
                'verbose_name_plural': 'Data Import Markers',
            },
        ),
    ]
